# Generated by Django 4.1.4 on 2023-01-17 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="description",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date created"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
